In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

oecd_countries = ["Australia", "Austria", "Belgium", "Canada", "Chile", "Colombia", "Costa Rica",
            "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany",
            "Greece", "Hungary", "Iceland", "Ireland", "Israel", "Italy", "Japan", 
            "Latvia", "Lithuania","Luxembourg", "Mexico", "Netherlands", "New Zealand", "Norway",
             "Poland","Portugal", "Slovakia", "Slovenia", "South Korea", "Spain", "Sweden",
             "Switzerland", "Turkey", "United Kingdom", "United States"]

hw_data = pd.read_excel("Copy of EFWAndRGDP.xls")
hw_data[hw_data["Countries"].isin(oecd_countries)]

,ISO_Code_3,Year,ISO_Code_2,World Bank Region,"World Bank Current Income Classification, 1990-present (L=Low income, LM=Lower middle income, UM=Upper middle income, H=High income)",Countries,Summary,Size of Government,Legal System and Property Rights,Sound Money,Freedom to Trade Internationally,Regulation,Standard Deviation of the 5 EFW Areas,RGDP Per Capita
135,AUS,1970,AU,East Asia & Pacific,NaN,Australia,7.291154,6.863768,7.775615,9.581113,5.882101,6.335298,1.462900,19166.0000
136,NaN,1975,AU,East Asia & Pacific,NaN,Australia,7.002204,6.255684,8.034445,8.346907,5.692162,6.761980,1.140578,20993.0000
137,NaN,1980,AU,East Asia & Pacific,NaN,Australia,7.316469,6.339449,8.037057,9.085686,5.841104,7.389934,1.302266,22972.0000
138,NaN,1985,AU,East Asia & Pacific,NaN,Australia,7.670016,6.259326,8.540345,9.089736,6.985368,7.469774,1.148037,24927.0000
139,NaN,1990,AU,East Asia & Pacific,H,Australia,7.927001,6.708215,8.398730,9.018318,7.661409,7.750886,0.865823,27373.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4288,NaN,2016,US,North America,H,United States,8.339536,7.252009,7.793107,9.814703,7.889129,8.952382,1.029060,53015.0000
4289,NaN,2017,US,North America,H,United States,8.379486,7.354358,7.802657,9.772320,7.921225,9.031901,0.994888,54007.7698
4290,NaN,2018,US,North America,H,United States,8.279612,7.409095,7.646530,9.772494,7.783384,8.784245,0.985924,55334.7394
4291,NaN,2019,US,North America,H,United States,8.249649,7.320058,7.644319,9.747903,7.829949,8.682216,0.979602,NaN
4292,NaN,2020,US,North America,H,United States,7.970000,6.790621,7.555009,9.626843,7.765508,8.109914,1.045188,NaN